### comments Index
GET http://localhost:3000/comments.json

### comments Create
POST http://localhost:3000/comments.json
Content-Type: application/json

{
"user_id": 1,
"comment": "test comment",
"state": "test state",
"bird_name": "test bird",
"image": "test chirp",
"chirp": "test call"
}

### comments Show
GET http://localhost:3000/comments/1.json

### comments Update
PATCH http://localhost:3000/comments/1.json
Content-Type: application/json

{
"user_id": 2,
"comment": "update comment",
"state": "update state",
"bird_name": "update bird",
"image": "update chirp",
"chirp": "update call"
}

### comments Destroy
DELETE http://localhost:3000/comments/3.json